- redis_consumer/consumers.py
Ensure that each file that is downloaded is the most recently uploaded file, by hashing the filename with the current time, so that each filename is unique.  The original filename is maintained in Redis as `original_filename` so that zip files can be re-assembled with the original folder structure.
Fixes #22
> Hash Uploaded Files

- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
passing a default value of `count=1000` to `scan_iter` in order to improve memory performance.
> Pass `count` to `scan_iter` to limit size of results in memory

- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
- redis_consumer/settings.py
The `ZipFileConsumer` now expires each hash that it adds to Redis once it is completed or failed.  Additionally, each failed hash is stored inside a dictionary along with the failure reason.  These are then saved to the original zip hash so users can track the failures of each image.
> Update ZipFileConsumer to expire hashes and track failures

- consume-redis-events.py
- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
- redis_consumer/settings.py
- redis_consumer/utils.py
Depending on the `status` of each zip file job, the ZipFileConsumer will perform work/update the job so that the next time it can be evaluated for its next status.  This prevents the zip consumers from hanging around waiting for a single job to complete while there are many zip jobs in the queue.
Additionally, the consumers each have their own processing queue (`processing-queue:hostname`).  This way items can be atomically moved from processing back to the work queue or removed from the processing queue with a single command.  This resolves an issue where consumers were getting scaled down while they have removed an item from the processing queue but before they placed it back, causing items to leak out of the work queue.
Hashes are also updated each time they are moved to a processing …
> ZipFileConsumers do not wait for jobs to finish but update the job data

- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
- redis_consumer/settings.py
No need to check the prefix of the key, as the key is already in the work queue.
> Update `is_valid_hash` to ignore key prefix

- consume-redis-events.py
- redis_consumer/consumers.py
- redis_consumer/settings.py
Removed any fancy logic for gRPC timeouts and backoff times.  just directly use the value of the environment variable `GRPC_TIMEOUT`.
Also, removed GracefulDeath, as it did not resolve the problems it was added to solve.
> all gRPC calls use a request_timeout of `GRPC_TIMEOUT`

- redis_consumer/consumers.py
- redis_consumer/processing.py
- redis_consumer/processing_test.py
- redis_consumer/settings.py
Scaling the dataprocessing API has proven to be a significant bottleneck, and the seemingly obvious way to move forward is to do the data processing directly on the redis consumer.  This will remove the latency between tf-serving requests and hopefully speed up our performance significantly.
The data processing API could make a comeback in the future, but while it is being optimized, let's just do the work on the CPU we have.
> Remove the streaming data processing requests and do the data processing directly

- redis_consumer/consumers.py
A bug was introduced in #45 that sliced into the last element of the list of results to pass to the post-processing function.  This is only applicable for panoptic models, and caused a breaking change for single predictions.  There is still a `TODO` for not just picking out the last element of the results list, but now we check that `image` is in fact a list before slicing.
> Fixed bug for postprocess images and lists of images

- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
After `_consume` is called, the consumer decides what to do with the key based on its status, which it fetches from Redis after the job is finished. During high volume runs, Redis may return slightly stale data.  This causes keys that are `done` getting put back into the work queue, causing them to be re-processed.
To resolve this, `_consume` returns the most recent status and the consumer uses this resulting status to decide what to do with the key.  This reduces the number of Redis calls and ensures we are not using stale data when moving the keys around.
* Updated `cleanup` to set the final status and log
* `_consume` returns the status most recently set status which `consume` then uses to determine whether to put the key back for future work or remove it.
* Added …
> Consumer._consume() returns the current status of the job.

- redis_consumer/consumers.py
- redis_consumer/consumers_test.py
- redis_consumer/processing.py
- redis_consumer/settings.py
- redis_consumer/utils.py
- redis_consumer/utils_test.py
- requirements.txt
- Create new tensorflow serving consumer class to manage functions associated with predict calls
- Modify ImageConsumer and TrackingConsumer to inherit from TensorFlowServingConsumer
- New images go through scale detection and rescaling before segmentation. Scale is restored before returning image to user
- Label detection model classifies each image as nuclear, brightfield or fluorescent cytoplasm
- Settings.py contains additional parameters including which model to use in each label case
- Scale and label predictions are generated on a subsampling of input data
- Tracking predicts scale and label on the whole stack and then passes those values to the ImageConsumer
> Enable scale and label type detection

- requirements.txt
Pin `deepcell-tracking` to the new release, 0.2.4.
> Update deepcell-tracking to 0.2.4

- redis_consumer/consumers.py
- redis_consumer/settings.py
The tracking-consumer currently pushes all segmentation work into the hard-coded `"predict"` queue.  This has been changed to use an environment variable, `SEGMENTATION_QUEUE`.  This allows a customized segmentation pipeline based on environment variables.
> Add SEGMENTATION_QUEUE env var for tracking-consumer

- .travis.yml
- docs/rtd-requirements.txt
- docs/source/conf.py
* Update `docs/conf.py` to be general to python 2 and 3.
* Update `Sphinx` to `>=1.8.5` to allow python 2 to install it.
Is 2.3.1 a required version for a particular reason? If so, this may not work.
> Update for python 2 support.

- redis_consumer/grpc_clients.py
Removes an `if model_version > 0` conditional statement during PredictClient request construction. if `model_version <= 0` the version is not assigned to the request, and tf-serving will use the default value of the latest version available. This may cause data to be sent to the incorrect model.
> Always assign model_version in the PredictClient.

- README.md
- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/image_consumer_test.py
- redis_consumer/settings.py
The environment variable `TF_TENSOR_NAME` is now unnecessary, as that information is stored within the GetModelMetadata response.
However, the current `TensorFlowServingConsumer.predict` method is only built for single-input models. If they require more than one input, they will fail.
Fixes #95
> Replace TF_TENSOR_NAME with ModelMetadata response.

- requirements.txt
* Fixes bugs in `tile_image` and `untile_image`.
* Fixes `phase_preprocessing` for non-float data.
* Removes `fgbg` reference in `deep_watershed` postprocessing.
> bump deepcell-toolbox to 0.4.0

- README.md
- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/tracking_consumer.py
- redis_consumer/settings.py
- redis_consumer/storage.py
- redis_consumer/storage_test.py
Using exponential backoff is a best practice according to the GCS docs.
This PR removes the `backoff` argument to `Storage` classes, and replaces it with `max_backoff`, which defaults to the environment variable `STORAGE_MAX_BACKOFF`.
`Storage` clients will now keep track of the number of retries it has attempted and will calculate a backoff time that scales exponentially with the attempt count, instead of just being a constant backoff of `backoff` seconds.
The `ZipFileConsumer` has also been updated to upload the folder as `/output/<UUID>/typical/file/path.jpg`. This way the consumer does not overwrite old data with the same name, driving down the "update requests" which has a one request-per-second limit.
---
Fixes #108
> Change Storage client to use exponential backoff.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
Invalid hashes should not be put back into the work queue. Now, each queue has its own consumer, so if one consumer finds an item invalid, they all will - and the item just bounces from consumer to consumer forever.
Instead, the item is removed from the consumer's processing queue and its status is set to "failed".
> fail invalid hashes to remove them from the job queue.

- .coveragerc
- .travis.yml
- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/image_consumer_test.py
- redis_consumer/consumers/tracking_consumer.py
- redis_consumer/consumers/tracking_consumer_test.py
- redis_consumer/redis_test.py
- redis_consumer/storage.py
- redis_consumer/storage_test.py
- redis_consumer/testing_utils.py
- redis_consumer/utils_test.py
- requirements-test.txt
`pytest-mock` and `fakeredis` allow us to more directly patch the functions we need to patch instead of the less rigorous monkeypatching we had before. This PR pushes the consumer tests all up to nearly 100%, though I also removed the `grpc_clients` from the coverage ignore, so the coverage will not be changed much.
Also, common testing classes have been moved into the `testing_utils` file for better sharing among consumer tests.
> Improved testing coverage using fakeredis and pytest-mock

- .coveragerc
- .travis.yml
- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/image_consumer.py
- redis_consumer/consumers/image_consumer_test.py
- redis_consumer/consumers/mibi_consumer.py
- redis_consumer/consumers/mibi_consumer_test.py
- redis_consumer/consumers/tracking_consumer.py
- redis_consumer/consumers/tracking_consumer_test.py
- redis_consumer/redis_test.py
- redis_consumer/settings.py
- redis_consumer/storage.py
- redis_consumer/storage_test.py
- redis_consumer/testing_utils.py
- redis_consumer/tracking.py
- redis_consumer/tracking_test.py
- redis_consumer/utils_test.py
- requirements-test.txt
This PR updates the MIBI branch with the new testing changes in master, and updates the mibi tests to better use the new testing_utils.py.
It also updates the MibiConsumer to inherit from the ImageFileConsumer so that we can make better use of the already built-in preprocess and postprocess functions. Just needed to add some keys to the `settings.PROCESSING_FUNCTIONS` object to make it all connect.
I just have a concern about the `get_image` call, as .tiff files automatically add a single-dimension channel...but these images already have a channel-dim of 2 I think.
> Update MIBI consumer to inherit from ImageFileConsumer.

- requirements.txt
The new patches resolve a versioning compatibility issue with newer versions of OpenCV.
> Update deepcell-toolbox and deepcell-tracking to latest patches.

- .travis.yml
- requirements-test.txt
Travis uses `pytest==4.X` for the Python 3.5 environment, which causes issues with a new release of `pytest-mock`. Instead of pinning `pytest>=5.X`, which does not support Python 2.7, we can `--upgrade` the requirements-test.txt file to update already installed dependencies.
> Fix test dependencies for Python 3.5 versioning issue.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/settings.py
set default `MAX_IMAGE_HEIGHT` and `MAX_IMAGE_WIDTH` and raise an error if `predict()` finds a larger image.
Closes #127
> Set a maximum image height/width.

- redis_consumer/consumers/multiplex_consumer.py
- redis_consumer/consumers/multiplex_consumer_test.py
- redis_consumer/processing.py
- redis_consumer/settings.py
- requirements.txt
Updates the multiplex model to the newest version
- Bump model version from 3 to 4 in GCS bucket
- Modify test functions for 2-head rather than 4-head output
- Update post-processing functions to use new versions in deepcell.applications
> Updated multiplex model

- redis_consumer/consumers/multiplex_consumer.py
- redis_consumer/processing.py
- redis_consumer/processing_test.py
- redis_consumer/settings.py
This provides a way for us to modify the post-processing params that are sent to the consumer.
Let me know if you think it would be better to have this somewhere else before I start moving forward
> separate wrapper function

- requirements-test.txt
Currently getting the following error which is new in PyTest 6.x:
```
Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.
See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.
```
> use pytest 5.x for now to resolve issue with pep8 test collections in 6.x

- redis_consumer/settings.py
Passing an empty string as an environment variable does not work, as the variable is ignored and the default value is used. By using `"none"` as a key, we can specifically tell the consumers to not process the data and to just return the model results directly.
> Add a "none" pre/post-process option to do nothing

- requirements.txt
The newest toolbox release has a bugfix for images with a blank channel. This bumps the required toolbox version so we can deploy that fix to deepcell.org
> Bump toolbox version

- redis_consumer/consumers/base_consumer.py
Not all models have "prediction" as a key, the consumers should accept all outputs.
This change decouples the consumers from the model export step.
> Return all output signatures from gRPC response.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/image_consumer.py
- redis_consumer/consumers/multiplex_consumer.py
- redis_consumer/settings.py
This PR fixes a bug that allows a user to set the `scale` value to very large values which will crash the consumer. Instead, the value is compared with new environment variables `MIN_SCALE` and `MAX_SCALE` and a `ValueError` is raised if the value is outside the range.
This introduces a new method `get_image_scale` on the base class `TensorFlowServingConsumer`, which can be called by the downstream classes.  `detect_scale` is also defined in the base class, though it just returns a default value of `1` and relies on the child classes to implement any detection via models.  This required changing the base class of `MultiplexConsumer` to `TensorFlowServingConsumer`.
> Set a MAX_SCALE and MIN_SCALE, raise ValueError if provided scale is outside.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
The current `predict_small_image` function assumes that small images small across both dimensions. This leads to an error with a negative pad value if one of the dimensions is appropriately sized and the other is not. 
I added in logic to add zero padding for dimensions that are at the threshold, with non-zero padding for the small side of the image.
> Padding bugfix

- redis_consumer/consumers/image_consumer_test.py
- redis_consumer/consumers/multiplex_consumer_test.py
- redis_consumer/testing_utils.py
* Mock `MultiplexConsumer.postprocess` during the consumer tests to reduce ~80% of total test time (20s -> 4s).
* Move `make_model_metadata_of_size` to `testing_utils.py` to be re-used in each consumer.
* Add model shapes that straddle either side of too big and too small to test suite.
* General code readability changes.
> Mock MultiplexConsumer postprocessing during tests to reduce 80% of test time.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/image_consumer.py
- redis_consumer/consumers/multiplex_consumer.py
Use `deepcell_utils.resize` instead of `skimage.transform.rescale`  in `save_output`. This guarantees the output shape will be the same as the input image.
Fixes #145
> Resize outputs to target shape in `save_output`.

- redis_consumer/consumers/base_consumer.py
A bug was introduced causing the output filenames to be changed from: `input_filename_feature_0.tif` to `input_filename_0_feature_0.tif`.
> Revert output filename suffix.

- .github/workflows/tests.yaml
- redis_consumer/consumers/__init__.py
- redis_consumer/consumers/mesmer_consumer.py
- redis_consumer/consumers/mesmer_consumer_test.py
- redis_consumer/settings.py
- requirements.txt
Refactor consumer names and the `MULTIPLEX_MODEL` to `MESMER_MODEL`.
This PR also allows the compartment to be passed to `.predict` using the `MESMER_COMPARTMENT` environment variable. The outputs are defined by `deepcell.applications.Mesmer` but will be multiple files in the same zip archive.
However, this introduces an incompatibility with `kiosk-imagej-plugin` which can [only open a single tiff file](https://imagej.nih.gov/ij/developer/api/ij/io/Opener.html#openURL-java.lang.String-) from the zip file.
`deepcell` is also updated to 0.9.0 which supports the `Mesmer` application and drops support for Python 3.5.
Fixes #136.
> Refactor MultiplexConsumer to MesmerConsumer.

- redis_consumer/grpc_clients_test.py
Add tests for `PredictClient.predict` and `PredictClient.get_model_metadata`.
There are two more remaining untested gRPC client functions:
- `insecure_channel`
- `_retry_grpc`
> Add tests for PredictClient gRPC methods.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/mesmer_consumer.py
- redis_consumer/consumers/mesmer_consumer_test.py
- redis_consumer/consumers/segmentation_consumer.py
- redis_consumer/consumers/segmentation_consumer_test.py
- redis_consumer/consumers/tracking_consumer.py
`channels` is expected to be a comma-separated string of integers, which allows the consumer to select a subset of channels from the image and re-orders them as input to the model.
For example, if an image has 4 channels, then a `channels` value of `"0"` selects the first channel of the image, while `"2,3"` selects the final 2 channels of the image.  A value of `"3,2"` also selects the final two images, but reorders them so that channel 3 is now in the channel 0 spot.
> Allow optional channels to be defined to select a subset of channels for the job.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
This size check was accidentally dropped when we migrated to using `deepcell` as the job definition. This PR re-introduces the check in the `validate_model_input` function.
> Validate image is smaller than MAX_IMAGE_HEIGHT and MAX_IMAGE_WIDTH

- redis_consumer/consumers/mesmer_consumer.py
Somewhere the `predicting` status stopped getting set for `MesmerConsumer`.
This PR simply adds it back in right before the application object is created, just like in `SegmentationConsumer`.
> Add predicting status update to MesmerConsumer

- redis_consumer/consumers/tracking_consumer.py
- redis_consumer/settings.py
Introduces new environment variable `MAX_IMAGE_FRAMES` which the `TrackingConsumer` compares its input against. If the input image has more frames, then an error is thrown.
This is due to a 1200 frame movie being uploaded causing a crash loop during tracking. (Segmentation of all 1200 frames worked as expected).
> TrackingConsumer throws an error if input has more frames than MAX_IMAGE_FRAMES

- redis_consumer/grpc_clients.py
- redis_consumer/grpc_clients_test.py
Fixes #167 
Ignore all negative dimensions when calculating batch size for the `GrpcModelWrapper`. This PR ensures that the batch size calculated will never be negative, but does not ensure that the batch size calculated will be optimal if there are many unknown dimensions.
> Ignore negative batch dimensions when calculating batch_size.

- redis_consumer/consumers/base_consumer.py
- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/mesmer_consumer.py
- redis_consumer/consumers/mesmer_consumer_test.py
- redis_consumer/consumers/segmentation_consumer.py
- redis_consumer/consumers/segmentation_consumer_test.py
Detects the dimension ordering for 2D and 3D data for channels first or channels last, and placed in Redis under the key `dim_order`.
This facilitates handing off the dim ordering to downstream visualization services.
Fixes #169
> Add new `detect_dimension_order` to detect the dim ordering string.

- Dockerfile
- redis_consumer/consumers/tracking_consumer.py
- redis_consumer/consumers/tracking_consumer_test.py
- redis_consumer/testing_utils.py
- redis_consumer/utils.py
- redis_consumer/utils_test.py
- requirements-no-deps.txt
- requirements.txt
- Update base image to Python 3.9-slim-buster.
- Add `tifffile` to requirements and remove `scikit-image`. The project depends on `tifffile` which is no longer included in `skimage` versions that are supported by newer Python versions.
- Update a few dependencies to their latest patches.
> Update dependencies and upgrade Docker base image.

- docs/source/conf.py
- docs/source/redis_consumer.consumers.rst
- redis_consumer/consumers/__init__.py
- redis_consumer/consumers/caliban_consumer.py
- redis_consumer/consumers/caliban_consumer_test.py
- redis_consumer/settings.py
- requirements.txt
Similar to #160, we are renaming the tracking workflow from Tracking to Caliban. The old options are still supported (tracking consumer type, TRACKING_MODEL, etc) but have been deprecated in favor of the caliban versions.
Additionally, the drift correction option has been removed, as it has never worked and relies on deprecated skimage code. Removes `scikit-image` from the dependencies, as the drift correction is the only place where it is used.
> Refactor TrackingConsumer to CalibanConsumer.

- Dockerfile
- redis_consumer/consumers/__init__.py
- redis_consumer/consumers/polaris_consumer.py
- redis_consumer/consumers/polaris_consumer_test.py
- redis_consumer/settings.py
- requirements.txt
Adding Polaris consumer and tests
> Adding Polaris consumer

- docs/rtd-requirements.txt
> Resolve jinja2 dependency error for sphinx

- redis_consumer/consumers/caliban_consumer.py
This PR updates the `channels` value for segmentation hashes created by the Caliban consumer. The changed format in [this PR](https://github.com/vanvalenlab/kiosk-frontend/pull/182).
> Update assignment for channels variable in Caliban consumer

- redis_consumer/consumers/base_consumer_test.py
- redis_consumer/consumers/caliban_consumer.py
- redis_consumer/consumers/polaris_consumer.py
- redis_consumer/consumers/polaris_consumer_test.py
- redis_consumer/consumers/segmentation_consumer.py
- redis_consumer/consumers/segmentation_consumer_test.py
- redis_consumer/settings.py
- redis_consumer/testing_utils.py
- redis_consumer/utils.py
- redis_consumer/utils_test.py
This PR adds support for multi-batch images for the segmentation and Polaris consumers. The segmentation consumer receives a variable `dimension_order` from the frontend (see [this PR](https://github.com/vanvalenlab/kiosk-frontend/pull/193)). This variable has been added to the data generated by the Polaris consumer for segmentation jobs.
We have also added more comprehensive testing of the segmentation consumer for input images of different dimension orders. This involved changes to the `DummyStorage` object to allow the dimensions of the images it generates to be specified. 
We have removed a line from the `get_image` utils function that expands the dimensions of loaded TIFF files by default, because this behavior complicated the handling of images with dimensions BXYC or CXYB. This …
> Add multi-batch prediction for the segmentation and Polaris consumers

- .github/workflows/tests.yaml
This PR introduces a change to cache the pip environment created to run the test Github action. With this change the tests run in under 2 minutes instead of 7-8 minutes.
> Cache pip environment for Github actions

- redis_consumer/grpc_clients.py
- requirements.txt
This PR makes changes to expose the output names of the GRPC-wrapped model. These changes allow the outputs of the TF-served model to be formatted into a dictionary. They are related to [this spots PR](https://github.com/vanvalenlab/deepcell-spots/pull/22).
> Expose GRPC model output names

- redis_consumer/grpc_clients.py
This PR fixes [this issue](https://github.com/vanvalenlab/kiosk-console/issues/458). The GRPC client returns a dictionary with keys corresponding to the output names. These names were previously sorted but the sorted keys were not saved. Therefore, when these keys were exposed and used, sometimes they were in the wrong order.
> Save and expose sorted output_names
